POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "zack", "password": "Pass1234!"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "zack", "password": "Pass1234!", "email": "zack@gmail.com"}

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 54d8cec3c59800cc217d8358c31193747aacf5f9

{}